#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'build'

import sys

def options(ctx):
   ctx.load('g++')
   ctx.load('gcc')

def configure(ctx):
   ctx.load('g++')
   ctx.load('gcc')

   ctx.env.append_value('CXXFLAGS', ['-O2', '-fPIC', '-Wall', '-pipe'])


def build(ctx):
   pass
#   ctx(
#      features     = 'cxx cxxprogram', 
#      source       = 'ex1.cpp',
#      target       = 'ex1',
#      includes     = '. ../',
#      uselib       ='VIENNAUTILS'
#   )


