/*=======================================================================
Copyright 1992 -- 2009, Institute for Microelectronics, TU Vienna.

                                 ViennaIPD
                             -----------------

LICENSE:  see ViennaIPD/LICENSE

AUTHORS:  Members of the Institute for Microelectronics, TU Vienna

=======================================================================*/

/** @file ipdscan.c
    @brief A lexical scanner generated by GNU flex used for scanning the .ipd files
*/


#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MIIPDNOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>
#include <iostream>
#include <fstream>
using namespace std;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_IPDNORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_accept[150] =
    {   0,
       35,   35,   47,   47,    0,    0,    0,    0,   56,   46,
       45,   42,   43,   44,   37,   34,    3,   46,   46,   35,
       46,    7,   24,   23,   30,   25,   31,   36,   35,   36,
       36,   10,   36,    9,   36,   36,   36,   36,   36,   46,
       47,   49,   48,   53,   54,   53,   52,   52,   55,   42,
       43,   37,   29,    1,    0,    0,    0,   26,   35,    5,
        0,    4,    8,    5,    7,    0,    0,   32,    0,   28,
       33,   35,   36,   36,   36,   36,   36,   36,   36,   36,
       13,   11,   36,   36,   27,   47,   48,   48,   50,   53,
       53,   53,   53,    0,   51,    0,    0,    0,    0,    0,

        8,    5,    0,    6,    0,    0,   36,   20,   17,   36,
       19,   36,   18,   36,   36,   12,    0,    0,    0,    0,
        5,    0,    0,    0,    0,   36,   16,   36,   36,   14,
        0,    0,    0,    0,    0,   38,   39,   22,   15,   21,
        0,    0,    0,   40,   41,    0,    2,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    3,    4,    5,
        3,    3,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   10,    1,    1,   11,    1,   12,
       13,   14,   15,    1,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
        1,   26,    1,   27,   24,    1,   28,   24,   29,   30,

       31,   32,   24,   24,   33,   34,   35,   36,   24,   37,
       38,   39,   24,   40,   41,   42,   43,   44,   24,   45,
       46,   24,   47,   48,   49,   27,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    2,    3,    1,    2,    1,    4,    1,
        1,    1,    5,    6,    1,    7,    1,    8,    1,    1,
        2,    1,    1,    9,    9,    1,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    1,    1,   10
    } ;

static yyconst short int yy_base[171] =
    {   0,
        0,    0,   45,   46,   43,   44,   58,   68,  411,  412,
      412,  406,    0,  412,  402,  386,   45,   51,  396,   58,
       66,   70,  412,  412,   56,  384,  383,   66,   78,   71,
       81,   83,   88,   84,   86,   93,  102,  103,  105,  356,
        0,  412,  108,  377,  412,  128,   83,  412,  412,  398,
        0,  389,  412,  412,  111,  134,  358,  412,  124,  121,
      118,  412,    0,  130,  131,  135,    0,  412,    0,  412,
      412,  141,  144,  147,  148,  149,  150,  154,  156,  157,
      163,  170,  171,  175,  412,    0,  187,  191,  412,  362,
      201,  361,  202,  186,  412,    0,    0,  349,  197,  173,

        0,  195,  347,  346,  333,  286,  202,  205,  206,  207,
      208,  209,  215,  222,  221,  228,  315,  276,  273,  257,
      249,  236,  228,  191,  216,  229,  230,  231,  237,  238,
      196,  204,  145,  165,  139,  412,  412,  244,  245,  247,
      160,  135,   96,  412,  412,   93,  262,  269,  412,  276,
      286,  296,  306,  310,  313,  322,  332,  342,  352,  362,
      366,  375,   81,   55,   48,   47,  381,  383,  389,  391
    } ;

static yyconst short int yy_def[171] =
    {   0,
      149,    1,  150,  150,  151,  151,  152,  152,  149,  149,
      149,  149,  153,  149,  149,  149,  149,  149,  149,  154,
      149,  149,  149,  149,  149,  149,  149,  155,  154,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  149,
      156,  149,  157,  158,  149,  159,  160,  149,  149,  149,
      153,  149,  149,  149,  149,  149,  149,  149,  154,  149,
      161,  149,  162,  149,  149,  149,  163,  149,  164,  149,
      149,  154,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  149,  156,  157,  157,  149,  158,
      159,  158,  159,  160,  149,  165,  166,  149,  149,  161,

      162,  149,  149,  149,  167,  168,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  169,  170,  149,  149,
      149,  149,  167,  168,  149,  155,  155,  155,  155,  155,
      149,  169,  170,  149,  149,  149,  149,  155,  155,  155,
      149,  149,  149,  149,  149,  149,  149,  149,    0,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149
    } ;

static yyconst short int yy_nxt[462] =
    {   0,
       10,   11,   10,   12,   13,   14,   15,   16,   17,   18,
       19,   10,   10,   10,   10,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   10,   29,   30,   28,   31,
       32,   33,   28,   34,   35,   28,   36,   28,   37,   28,
       28,   38,   28,   28,   28,   39,   10,   40,   10,   42,
       42,   45,   45,   54,   56,  118,  117,   56,   43,   43,
       48,   48,   49,  106,   48,   55,   48,   67,   46,   46,
       48,   48,   49,   59,   48,   60,   48,   68,   48,   62,
       48,   72,   63,   57,   59,   64,   72,   65,   48,  105,
       48,   95,   72,   59,   66,  149,   72,   72,   72,   72,

       66,   72,   69,   72,   59,   95,   74,   72,   72,   72,
       72,   76,   72,   75,   72,   79,   80,   72,   72,   72,
       72,   88,   96,  147,   89,  146,   77,   78,   72,   72,
       81,   72,   90,   72,   82,   84,   90,   56,   60,   59,
       56,  149,   83,  145,   72,   99,   64,  102,   65,  103,
       59,   99,  104,   93,   99,   66,   72,   97,  149,   72,
       99,   66,   72,   72,   72,   72,   57,   72,  144,   72,
       72,   72,   72,   72,   72,   72,   72,  110,   72,  107,
       72,  143,   72,   72,  109,   72,   72,  142,   72,   72,
       72,  112,  108,  134,   95,  111,   72,   72,  114,   72,

      149,   72,  113,  149,   88,   90,   90,   89,   95,   90,
       90,  120,  102,  115,  121,  116,  131,   72,  141,   99,
       72,   72,   72,   72,   72,   99,   93,   93,   72,  126,
       72,   72,   72,   72,   72,   72,   72,   72,  137,  125,
      122,   72,  127,   72,   72,   72,   72,   72,   72,  128,
      129,  130,   72,   72,   72,   72,   72,   72,  136,   72,
       72,  139,   72,   72,   72,  148,  121,  140,  148,  138,
       72,   72,  148,   72,  121,  148,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   51,   51,  135,   51,
       51,   51,   51,   51,   51,   51,   61,   61,   61,   73,
       73,   73,   86,   86,  134,   86,   86,  131,   86,   86,
       86,   86,   87,   87,  125,   87,   87,   87,   87,   87,
       87,   87,   90,   90,   90,  122,   90,   90,   90,   90,
       90,   90,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   94,  104,  104,   94,   94,   94,   94,   94,
       94,   94,  100,  100,  100,  101,  101,  119,  101,  101,
      101,  101,  101,  101,  101,  123,   91,   91,  123,  123,
      124,  124,  124,  132,   98,   52,  132,  132,  133,  133,

      133,   50,   91,   85,   71,   70,   58,   53,   52,   50,
      149,    9,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149
    } ;

static yyconst short int yy_chk[462] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    6,   17,   18,  166,  165,   18,    3,    4,
        7,    7,    7,  164,    7,   17,    7,   25,    5,    6,
        8,    8,    8,   20,    8,   20,    8,   25,    7,   21,
        7,   28,   21,   18,   20,   22,   30,   22,    8,  163,
        8,   47,   28,   29,   22,   29,   31,   30,   32,   34,

       22,   35,   25,   33,   29,   47,   30,   31,   36,   32,
       34,   31,   35,   30,   33,   33,   35,   37,   38,   36,
       39,   43,   55,  146,   43,  143,   32,   32,   37,   38,
       36,   39,   46,   61,   37,   39,   46,   56,   60,   59,
       56,   59,   38,  142,   61,   60,   65,   64,   65,   66,
       59,   60,   66,   46,   64,   65,   72,   55,   72,   73,
       64,   65,   74,   75,   76,   77,   56,   72,  141,   78,
       73,   79,   80,   74,   75,   76,   77,   77,   81,   74,
       78,  135,   79,   80,   76,   82,   83,  134,  100,   81,
       84,   79,   75,  133,   94,   78,   82,   83,   83,  100,

       87,   84,   80,   87,   88,   91,   93,   88,   94,   91,
       93,   99,  102,   83,   99,   84,  132,  107,  131,  102,
      108,  109,  110,  111,  112,  102,   91,   93,  107,  107,
      113,  108,  109,  110,  111,  112,  115,  114,  125,  124,
      123,  113,  110,  116,  126,  127,  128,  115,  114,  112,
      114,  115,  129,  130,  116,  126,  127,  128,  122,  138,
      139,  128,  140,  129,  130,  147,  121,  129,  147,  126,
      138,  139,  148,  140,  120,  148,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  152,  152,  152,  152,

      152,  152,  152,  152,  152,  152,  153,  153,  119,  153,
      153,  153,  153,  153,  153,  153,  154,  154,  154,  155,
      155,  155,  156,  156,  118,  156,  156,  117,  156,  156,
      156,  156,  157,  157,  106,  157,  157,  157,  157,  157,
      157,  157,  158,  158,  158,  105,  158,  158,  158,  158,
      158,  158,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  160,  104,  103,  160,  160,  160,  160,  160,
      160,  160,  161,  161,  161,  162,  162,   98,  162,  162,
      162,  162,  162,  162,  162,  167,   92,   90,  167,  167,
      168,  168,  168,  169,   57,   52,  169,  169,  170,  170,

      170,   50,   44,   40,   27,   26,   19,   16,   15,   12,
        9,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/markus/vproject/ipd/ipdscan.l"
#define INITIAL 0
/*
static char const _rcsid_ [] = "$Id: ipdscan.l,v 1.15 2005/02/10 07:01:17 mmntuser Exp $";
*/
/*=======================================================================
                              vproject / ipd
                             ----------------
                                ipdscan.l

Contents: Scanner for the input deck programming language (IPL)


AUTHORS:  RK   Robert Klima,      Institute for Microelectronics, TU Vienna
          BR   Bernhard Reinisch, Institute for Microelectronics, TU Vienna


  who when        what
-------------------------------------------------------------------------
  BR  1997        first coding
  RK  1998-04-14  Code changed for new input deck.
=======================================================================*/
/*-------------------------------------------------------------------------

----------------------------------------------------------
Expression  Matches                        Example
--------------------------------------------------
c           any non-operator character c   a
\c          character c literally          \*
"s"         string s literally             "**"
.           any character but newline      a.*b
^           beginning of line              ^abc
$           end of line                    abc$
[s]         any character in s             [abc]
[^s]        any character not in s         [^abc]
r*          zero or more r's               a*
r+          one or more r's                a+
r?          zero or one r                  a?
r{m,n}      m to n occurrences of r        a{1,5}
r1r2        r1 then r2                     ab
r1|r2       r1 or r2                       a|b
(r)         r                              (a|b)
r1/r2       r1 when followed by r2         abc/123
--------------------------------------------------
Table 1: Lex regular expressions (taken from [1, fig. 3.48]).
--------------------------------------------------
REFERENCES

[1]   Aho, Alfred V.; Ravi Sethi; Jeffrey D. Ullman: Compilers : prin-
      ciples, techniques  and tools.  Reading, Mass.:  Addison-Wesley,
      1986.

[2]   Johnson,  S.C.: Yacc  - yet  another compiler-compiler.  Murray
      Hill, N.J.: Bell Telephone Laboratories, 1974. (CSTR-32).

[3]   Lesk, M.E.: Lex  - a lexical  analyser  generator. Murray  Hill,
      N.J.: Bell Telephone Laboratories, 1975. (CSTR-39).

[4]   Schreiner, A.T.; H.G.  Friedman:  Introduction to  compiler con-
      struction with UNIX. Prentice-Hall, 1985.

[5]   Waite,  William M.;  Gerhard Goos:   Compiler construction.  New
      York:  Springer,  1985.   (Texts  and  monographs   in  computer
      science).

--------------------------------------------------
D       [0-9]
%%
{D}+(\.{D}+)?([Ee][+-]?{D}+)?
--------------------------------------------------
-------------------------------------------------------------------------*/
/* [SW]: the "template2" state is used for picking up a template %x template2 
"<("                    {CALC_TOKENPOS; BEGIN(template2); } [<][{(]{ID}[})][>] [SW]: <{VAR}> or <(VAR)> => VAR
"<{"                    {CALC_TOKENPOS; BEGIN(template2); }
<template2>{ID}         {CALC_TOKENPOS; return do_id();   }
<template2>")>"         {CALC_TOKENPOS; BEGIN(INITIAL);   }
<template2>"}>"         {CALC_TOKENPOS; BEGIN(INITIAL);   } */
/* the "comment2" state is used for
   picking up a comment which may use
   more than one lines. */
#define comment2 1

/* the "strg" state is used
   for picking up a string */
#define strg 2

/* the "incl" state is used
   for picking up a include filename */
#define incl 3

#line 94 "/home/markus/vproject/ipd/ipdscan.l"
#include "ipdP.h"
#include "ipdparse.ah"
#include <string.h>

/*MK because it is already defined in win defautls */
#ifdef DELETE 
#undef DELETE
#endif
#define	DELETE	267


#define YY_IPDNO_UNPUT
#define SIZE_OF_LINEBUFFER 500
  char             linebuf[SIZE_OF_LINEBUFFER] = ""; /* for better error recovery */
  int              tokenpos;                     /* for better error recovery */
#define RESET_TOKENPOS tokenpos = 0
#define CALC_TOKENPOS tokenpos += yyleng
  char           **currentComment = NULL;
#define MAX_INCLUDE_DEPTH 50
  char           **currentCommentArray[MAX_INCLUDE_DEPTH];
  YY_BUFFER_STATE  ipdIncludeStack[MAX_INCLUDE_DEPTH];
  int              ipdIncludeStackPtr = 0;
  int              ipdLineNoStack[MAX_INCLUDE_DEPTH];
  ipdIFL_t        *ipdFileStack[MAX_INCLUDE_DEPTH];
  int              commentNewLine = 0;
  int              ipdLineNo = 1;

/* Function declarations */
int do_const(double a);
int do_boolean(ipdBoolean a);
int do_integer(void);
int do_real(void);
int do_id(void);
int do_path(void);
void do_comment(int newLine, ipdBoolean isCStyle);
int do_string(void);
int do_template(void);
int do_include(void);
int do_NULLstring(void);

/*
  :=                      {CALC_TOKENPOS; return STORE_READ_ONLY;}
*/
#line 645 "/home/markus/vproject/ipd/ipdscan.ac"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_IPDNO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif


#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_IPDNO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_IPDNO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_IPDNO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_IPDNO_PUSH_STATE 1
#define YY_IPDNO_POP_STATE 1
#define YY_IPDNO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
 /*
#ifndef ECHO
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif
*/

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
   size_t ret_val = 0;
#line 140 "/home/markus/vproject/ipd/ipdscan.l"


#line 799 "/home/markus/vproject/ipd/ipdscan.ac"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 150 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 412 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 142 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_NULLstring();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 143 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; BEGIN(incl); return INCLUDE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 144 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; BEGIN(strg);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 145 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; BEGIN(comment2);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 146 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_real();}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 147 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_real();}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 148 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_integer();}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 149 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; do_comment(commentNewLine, ipdFALSE); commentNewLine = 1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 150 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return COMPLEX;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 151 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_const (ipd_E);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 152 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_const (ipd_PI);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 153 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_boolean (ipdTRUE);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 154 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_boolean (ipdFALSE);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 155 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_boolean (ipdTRUE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 156 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_boolean (ipdFALSE);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return EVAL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 158 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return DELETE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return KEY;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 160 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return EXT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 161 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return AUX;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 162 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return TRACE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 163 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return ALIAS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 164 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return SEMICOLON;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 165 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return COLON;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 166 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return ASSIGNMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 167 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return LOGIC_AND;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 168 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return LOGIC_OR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 169 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return EQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 170 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return NE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 171 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return LT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 172 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return GT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 173 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return LE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 174 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return GE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 176 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return IPDNOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 177 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_path();}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 178 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_id();}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 179 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; /* eat up spaces */ }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 181 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_template(); } /* [SW]: <(VAR)> => VAR */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 182 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_template(); } /* [SW]: <{VAR}> => VAR */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 184 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_template(); } /* [SW]: <(VAR)> => VAR */
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 185 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return do_template(); } /* [SW]: <{VAR}> => VAR */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 187 "/home/markus/vproject/ipd/ipdscan.l"
{
                           int i;
			   for (i=0;i<8;i++)
			      CALC_TOKENPOS;
			   /* eat up tabs   */
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 193 "/home/markus/vproject/ipd/ipdscan.l"
{
                           strncpy(linebuf, yytext+1,SIZE_OF_LINEBUFFER);
			   /* if strlen(yytext) > SIZE_OF_LINEBUFFER:
			      the string remains unterminated:
			      -> place a preventive \n at the end */
			   linebuf[SIZE_OF_LINEBUFFER - 2] = '\n';
			   linebuf[SIZE_OF_LINEBUFFER - 1] = '\0';
			   ipdLineNo++;
			   yyless(1); /* give back all but the \n to rescan */
			   RESET_TOKENPOS;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 204 "/home/markus/vproject/ipd/ipdscan.l"
RESET_TOKENPOS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 205 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return 0; /* EOT; zero is the termination-code */ }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 206 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return yytext[0]; /* return all unmatched chars */ }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 207 "/home/markus/vproject/ipd/ipdscan.l"
{ /* read anything that's not a '*' */
                           CALC_TOKENPOS;
			   do_comment(commentNewLine, ipdTRUE);
                           commentNewLine = 0;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 212 "/home/markus/vproject/ipd/ipdscan.l"
{/* read '*'s not followed by '/'s */
                           CALC_TOKENPOS;
			   do_comment(commentNewLine, ipdTRUE);
                           commentNewLine = 0;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 217 "/home/markus/vproject/ipd/ipdscan.l"
{
                           commentNewLine++;
			   ipdLineNo++;
			   RESET_TOKENPOS;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 222 "/home/markus/vproject/ipd/ipdscan.l"
{
                           CALC_TOKENPOS;
			   commentNewLine = 1;
			   if (yyleng > 2)
			   {
			      yytext[yyleng - 2] = '\0';
			      do_comment(commentNewLine, ipdTRUE);
			   }
                           BEGIN(INITIAL); /* return to normal scanning */
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 232 "/home/markus/vproject/ipd/ipdscan.l"
{ /* Include with file */
                          CALC_TOKENPOS;
                          BEGIN(INITIAL); /* return to normal scanning */
                          return do_include();
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 237 "/home/markus/vproject/ipd/ipdscan.l"
{CALC_TOKENPOS; return yytext[0]; /* return all unmatched chars */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 238 "/home/markus/vproject/ipd/ipdscan.l"
{
                           /* anything not a ": that's my string!; OLD: <strg>[^"]+ */
                           CALC_TOKENPOS;
			   return do_string();
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 243 "/home/markus/vproject/ipd/ipdscan.l"
{/* " end of string reached */
                           CALC_TOKENPOS;
                           BEGIN(INITIAL); /* return to normal scanning */
                        };
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment2):
case YY_STATE_EOF(strg):
case YY_STATE_EOF(incl):
#line 247 "/home/markus/vproject/ipd/ipdscan.l"
{
                           RESET_TOKENPOS;
			   if ((yyin))
			      fclose(yyin);
                           iiSetSuccessfullyParsedFiles(1 + iiGetSuccessfullyParsedFiles()); /* one more */
                           if (--ipdIncludeStackPtr < 0)
                           {
                              yyterminate();  /* end of parsing mainfile */
                           }
                           else
                           {
                              /* reload for calling file */
                              ipdLineNo = ipdLineNoStack[ipdIncludeStackPtr];
                              currentComment = currentCommentArray[ipdIncludeStackPtr];
			      commentNewLine = 0;
                              /* reload for calling file */
                              iiSetScannedFile(ipdFileStack[ipdIncludeStackPtr]);
                              yy_delete_buffer(YY_CURRENT_BUFFER);
                              yy_switch_to_buffer(ipdIncludeStack[ipdIncludeStackPtr]);
                           }
                           /* debug0("INCLUDE(<<EOF>>)\n"); */
                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 269 "/home/markus/vproject/ipd/ipdscan.l"
/*ECHO;*/
ret_val = fwrite( yytext, yyleng, 1, yyout ); /* [JW] capturing the ret_val to please the compiler .. */

	YY_BREAK
#line 1232 "/home/markus/vproject/ipd/ipdscan.ac"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_IPDNORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


void ipdFreeBuffer()
{
	yy_delete_buffer(YY_CURRENT_BUFFER);
}


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 150 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 150 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 149);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_IPDNO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_IPDNO_UNPUT */





#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{ 
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_IPDNO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_IPDNO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_IPDNO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_IPDNO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_IPDNO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_IPDNO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 269 "/home/markus/vproject/ipd/ipdscan.l"



/*-------------------------------------------------------------------------
    A parse (?) error occured, -> I'm in the scanner!
    Called by yyparse() on error ?!.
    print debug info,
    do some clean up.
-------------------------------------------------------------------------*/
void iiDumpScannerPosition(void)
{
   int       i;
   ipdIFL_t *fileList;

   fileList = iiGetScannedFile();

   if ((ipdPrivate.scannedFile))
   {
      /*MK added code to show line number at parser errors     */
      char           str[ipdERRORSTRLEN + 1];
      sprintf(str,"%s, line: %d\n",
		((fileList) && (fileList->fileName)) ?
		fileList->fileName : "?filename?",
		ipdLineNo );
      ipdErrorStrCatN(str, 0); 
      /* end added code */
      
      ipdStdLog("%s, line: %d\n",
		((fileList) && (fileList->fileName)) ?
		fileList->fileName : "?filename?",
		ipdLineNo);
   }
#if IPD_ON_ERROR_SHOW_ERRLINE
   ipdStdLog("%s\n", linebuf);
   ipdStdLog("%*serror-position\n", (int)strlen(linebuf)+1, "^");
#endif
   if ((ipdPrivate.scannedFile))
   {
      /*MK added code to show line number at parser errors     */
      char           str[ipdERRORSTRLEN + 1];
      for (i = ipdIncludeStackPtr-1 ; i >= 0 ; i-- )
      {
          sprintf(str,"%s, line: %d\n",
                 ((fileList) && (fileList->fileName)) ?
		  fileList->fileName : "?filename?",
		  ipdLineNo );
          ipdErrorStrCatN(str, 0); 
      }    
      /* end added code */
      
       
      for (i = ipdIncludeStackPtr-1 ; i >= 0 ; i-- )
      {
	 ipdStdLog(" included from file: \"%s\",  line: %d\n",
		   ((ipdFileStack[i]) && (ipdFileStack[i]->fileName)) ?
		   ipdFileStack[i]->fileName : "?filename?",
		   ipdLineNoStack[i]);
      }
   }
} /* iiDumpScannerPosition */

void yyerror(const char *s)
{
   if (!ipdGetErrorNumber())
      iiSetErrorNumber(ipdERR_PARSE);

   ipdIncludeStackPtr = 0;
   s = NULL; /* We do not need the string. Just to avoid warning "unused parameter" */
} /* yyerror */

void includeFile(ipdBoolean withSearchPath, char *includeFileName)
{
  ipdIFL_t *curFile;
  FILE *newin /* , *yyout */ ;

  CALC_TOKENPOS;
  if (ipdIncludeStackPtr >= MAX_INCLUDE_DEPTH)
  {
     ipdSetError(ipdERR_TOO_MANY_INCLUDES);
     return;
  }

  currentCommentArray[ipdIncludeStackPtr]  = currentComment;   /* store linecounter */
  if ((newin = iiFileOpen(includeFileName,
			 &curFile,
			 iiGetScannedFile()->file,
			 withSearchPath,
			 "r")))
  {
     ipdTreeNode_t *tn;

     ipdLineNoStack[ipdIncludeStackPtr]  = ipdLineNo;   /* store linecounter */
     ipdLineNo                           = 1;        /* reset for new include-file */
     ipdFileStack[ipdIncludeStackPtr]    = iiGetScannedFile();
     yyin                                = newin;
     iiSetScannedFile(curFile);                   /* store actual filename */
     ipdIncludeStack[ipdIncludeStackPtr] = YY_CURRENT_BUFFER;
     yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
     /* everything is stored, now count up */
     ipdIncludeStackPtr++;

     /* Create new node. */
     tn = iiCreateTreeNode(ipdINCLUDE);
     ipd_RETURNonERRORv;
     tn->node.sv.fullname = tn->node.sv.name = includeFileName;
     tn->node.sv.svu.icld.file = curFile;
     tn->node.sv.file = ipdFileStack[ipdIncludeStackPtr-1];
     tn->node.sv.lineno = ipdLineNoStack[ipdIncludeStackPtr-1];
     if (withSearchPath)
	tn->node.sv.svu.icld.flags = ipdIF_WITH_SEARCHPATH;
     iiConnectTreeNode(iiGetRoot(), tn);
  }
  else if (!(ipdGetErrorNumber()))
     ipdSetError(ipdERR_FILE_IPDNOT_FOUND, includeFileName);
} /* includeFile */

int do_boolean(ipdBoolean a)
{
  yylval.b = a;
  debug1("do_boolean(%s), ",(a == ipdTRUE) ? "TRUE" : "FALSE");
  return BOOLEAN;
} /* do_boolean */

int do_const(double a)
{
  yylval.d = a;
  debug2("do_const(%s=%#.16g), ",yytext,yylval.d);
  return REAL;
} /* do_const */

int do_integer(void)
{
  yylval.i = atol(yytext);
  debug1("do_integer(%li), ",yylval.i);
  if ((yylval.i == LONG_MAX) ||
      (yylval.i == LONG_MIN))
     ipdSetError(ipdERR_INTEGER_OVERFLOW);
  return INTEGER;
} /* do_integer */

int do_real(void)
{
  sscanf(yytext, "%lf", &yylval.d);
  debug1("do_real(%#.16g), ",yylval.d);
  return REAL;
} /* do_real */

int do_id(void)
{
  yylval.s = iiStrDup(yytext);
  debug1("do_id(%s), ",yylval.s);
  currentComment = NULL;
  commentNewLine = 0;
  return ID;
} /* do_id */

int do_template(void) /* [SW]: Resort string to get rid of the brackets. */
{
   int x;
   int diff = 2;
   do_id();

   /* What are we doing here?

      String template: "<{TEMPLATE}>"  
                   ==> Tpl.TEMPLATE__    _ == \0
      Normal template: <{TEMPLATE}>
                   ==> Tpl.TEMPLATE

   */

   /* String templates */
   if ((yylval.s[0] == '"') && (yylval.s[yyleng-1] == '"'))
   {
      for (x = yyleng - 3; x < yyleng; x++) yylval.s[x] = '\0';
      diff = 1;
   }

   for (x = yyleng - 1; x > 3; x--) 
   {
      /* printf("   Assigning: %c instead of %c\n", yylval.s[x - 1], yylval.s[x]); */
      yylval.s[x] = yylval.s[x - diff];
   }

   yylval.s[0] = 'T';
   yylval.s[1] = 'p';
   yylval.s[2] = 'l';
   yylval.s[3] = '.';

   /* printf("New string: %s\n", yylval.s); */
   return ID;
}

int do_path(void)
{
  yylval.s = iiStrDup(yytext);
  debug1("do_path(%s), ",yylval.s);
  return PATH;
} /* do_path */

void do_comment(int newLine, ipdBoolean isCStyle)
{
   if ((currentComment))
   {
      char *pos = yytext;

      if (!isCStyle)
	 pos +=2;
      while ((*pos) && (isspace((int)*pos)))
	 pos++;
      if ((*currentComment))
      {
	 char *newComment;
	 long  len;

	 if ((newComment = (char *)ipdMBalloc(strlen(*currentComment) +
					      strlen(pos) + 1 + newLine)))
	 {
	    strcpy(newComment, *currentComment);
	    len         = strlen(newComment);
	    while (newLine--)
	       newComment[len++] = '\n';
	    strcpy(newComment + len, pos);
	    ipdMBfree(*currentComment);
	    *currentComment = newComment;
	 }
      }
      else
	 *currentComment = iiStrDup(pos);
#if IPD_ipdDEBUG
      if ((*currentComment))
	 debug1("do_comment(%s), ",currentComment);
#endif /* IPD_ipdDEBUG */
   }
} /* do_comment */

int do_string(void)
{
  char *sFrom, *sTo;

  yylval.s = iiStrDup(yytext);
  sFrom = sTo = yylval.s;
  while (*sFrom)
  {
     if (*sFrom == '\\')
     {
	++sFrom;
	switch (*sFrom)
	{
	   case 'a': /*  bell */
	      *sTo++ = '\a';
	      sFrom++;
	      break;
	   case 'b': /*  backspace */
	      *sTo++ = '\b';
	      sFrom++;
	      break;
	   case 'f': /*  formfeed */
	      *sTo++ = '\f';
	      sFrom++;
	      break;
	   case 'n': /*  newline */
	      *sTo++ = '\n';
	      sFrom++;
	      break;
	   case 'r': /*  carriage return */
	      *sTo++ = '\r';
	      sFrom++;
	      break;
	   case 't': /*  horizontal tab */
	      *sTo++ = '\t';
	      sFrom++;
	      break;
	   case 'v': /*  vertical tab */
	      *sTo++ = '\v';
	      sFrom++;
	      break;
	   case '\\': /*  backslash */
	      *sTo++ = '\\';
	      sFrom++;
	      break;
           case '?': /*  question mark */
	      *sTo++ = '\?';
	      sFrom++;
	      break;
           case '\'': /*  single quote */
	      *sTo++ = '\'';
	      sFrom++;
	      break;
           case '\"': /*  double quote */
	      *sTo++ = '\"';
	      sFrom++;
	      break;
           case 'x': /*  hexadecimal number */
	      {
		 int c = 1000;

		 sFrom++;
		 if ((isdigit((int)*sFrom)))
		    c = *sFrom++ - '0';
		 else if ((*sFrom >= 'a') && (*sFrom <= 'f'))
		    c = *sFrom++ - 'a' + 10;
		 else if ((*sFrom >= 'A') && (*sFrom <= 'F'))
		    c = *sFrom++ - 'A' + 10;
		 if ((isdigit((int)*sFrom)))
		    c = (c << 4) + *sFrom++ - '0';
		 else if ((*sFrom >= 'a') && (*sFrom <= 'f'))
		    c = (c << 4) + *sFrom++ - '0' + 10;
		 else if ((*sFrom >= 'A') && (*sFrom <= 'F'))
		    c = (c << 4) + *sFrom++ - '0' + 10;
		 if (c < 1000)
		    *sTo++ = (char)c;
	      }
	      break;
	   default:
	      {
		 int c = 1000;

		 if ((*sFrom >= '0') && (*sFrom <= '7'))
		 {
		    c = *sFrom++ - '0';
		    if ((*sFrom >= '0') && (*sFrom <= '7'))
		       c = (c << 3) + *sFrom++ - '0';
		    if ((*sFrom >= '0') && (*sFrom <= '7'))
		       c = (c << 3) + *sFrom++ - '0';
		    if (c < 256)
		       *sTo++ = (char)c;
		 }
		 else
		    *sTo++ = *sFrom++;
	      }
	      break;
	}
     }
     else
	*sTo++ = *sFrom++;
  }
  *sTo = '\0';
  debug1("do_string(%s), ",yylval.s);
  return STRING_PART;
} /* do_string */

int do_NULLstring(void)
{
  yylval.s = NULL;
  debug1("do_NULLstring(%s), ",yylval.s);
  return STRING_PART;
} /* do_NULLstring */

int do_include(void)
{
   yylval.s = iiStrDup(yytext);
   debug1("do_include(%s), ",yylval.s);
   return INCLUDE_FILENAME;
} /* do_include */
